"""empty message

Revision ID: 82023631013c
Revises: 7686e4abb158
Create Date: 2024-03-31 11:05:47.656947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82023631013c'
down_revision = '7686e4abb158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('handle',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('handle',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
