"""empty message

Revision ID: 85c9e88a3fb1
Revises: fc12cf1a15c3
Create Date: 2024-03-31 11:17:37.624417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c9e88a3fb1'
down_revision = 'fc12cf1a15c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('handle')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.VARCHAR(length=40), nullable=True))

    # ### end Alembic commands ###
