"""empty message

Revision ID: fc12cf1a15c3
Revises: 3a3d45eabdc6
Create Date: 2024-03-31 11:12:13.268217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc12cf1a15c3'
down_revision = '3a3d45eabdc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('handle',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('handle',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###
